Refactor/tabs
italia/design-react-kit pull request #1129
Opened 2024-11-25 12:15 UTC by Virtute90

Fixes #1090 #1096

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `main` branch.
- [x] The unit tests pass locally with my changes (if applicable).
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [x] I have added necessary documentation (if appropriate).

#### Short description of what this resolves:

Implementazione del componente tab con react-bootstrap per una migliore gestione dei pattern ARIA

#### Changes proposed in this Pull Request:

Revisione completa del componente tab in tutte le sue varianti.

Lascio la PR in draft per capire se il lavoro fatto è conforme ai requisiti di accessibilità.

Mancano i seguenti passaggi per completare il componente e la documentazione:

- [ ] Concludere la documentazione dalle tab verticali
- [ ] Controllare i test sul componente

2024-12-03 09:51 UTC, Fupete requested changes
La selezione del tab item corrente — e il conseguente cambio del contenuto nel tab a seguire — deve avvenire solo per scelta consapevole dell'utente: al click/touch/`invio`/`spazio`. 

Nell'implementazione attuale degli esempi con i controlli, navigando da tastiera, avviene in automatico al solo navigare con le frecce tra i diversi tab item. Con la conseguenza che il solo esplorare le opzioni cambia il contenuto del tab panel.

2025-01-10 11:59 UTC, Virtute90 commented
@astagi @Fupete Esempi documentazione completati!

2025-01-10 13:36 UTC, Fupete requested changes
Nella [pagina completa di documentazione](https://design-react-jv1g52pwj-dip-trasformazione-digitale.vercel.app/?path=/docs/documentazione-componenti-tab--documentazione)si nota che navigando con le frecce (destra > destra > destra > ...) invece di ciclare negli item del componente corrente in cui sei entrato con un tasto Tab, passa al componente dell'esempio successivo... e così via. Deve ciclare tra gli item del componente corrente. Non si va al componente successivo con i tasti freccia. Si entra/esce col tasto Tab nel componente. Poi le frecce (su/giù e dx/sx) non devono portarti fuori o a componenti successivi ma solo ciclare tra gli item. cc @astagi @Virtute90 

![immagine](https://github.com/user-attachments/assets/94475c01-fea7-4467-a6b0-7cd6a6a9bb11)
 

![immagine](https://github.com/user-attachments/assets/8dd9f020-0843-475a-bb82-e5118cd857ee)

2025-01-10 16:43 UTC, astagi commented
@Fupete @Virtute90 risolto negli ultimi commit 🙌

2025-01-13 10:25 UTC, Fupete commented
@astagi il comportamento delle frecce ora è corretto, ciclando solo nello stesso tab. 

**Ma** purtroppo il tab stesso diventa un "keyboard trap" perché intrappola il focus. Premendo TAB entri nel componente, con le FRECCE navighi tra gli item. **Ma premendo nuovamente TAB** non esci più da componente. 

![immagine](https://github.com/user-attachments/assets/b465e840-48b1-463a-8b5b-ccfb12337002)

2025-01-13 16:09 UTC, Fupete commented
@astagi purtroppo ho notato che se col focus sul componente navighi fuori premendo nuovamente il tasto Tab, l'`aria-selected` dell'item selezionato diventa/rimane `false`. Quando torni sul componente (Shift-Tab per esempio per tornarci sopra) rimane `false`, non segnalando quindi più ai lettori di schermo l'elemento che è attivo/selezionato del tab.

2025-01-14 10:57 UTC, astagi approved these changes

2025-01-14 10:58 UTC, merged