Adding `alt` attribute to Icon components
italia/design-react-kit pull request #864
Opened 2022-10-10 08:04 UTC by dennybiasiolli

Fixes #860 

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (if applicable).
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [ ] I have added necessary documentation (if appropriate).

#### Short description of what this resolves:

This adds accessibility improvements for `Icon` and `HeaderBrand` components

#### Changes proposed in this Pull Request:

- stories(AutocompleteExample): removing a warning in tests

    `Parameter 'props' implicitly has an 'any' type`

- Icon: adding optional `alt` attribute in case of custom image

- HeaderBrand: adding `iconAlt` optional attribute

- Icon(assets): adding title element to svg icons

2022-10-11 07:04 UTC, dej611 requested changes
> HeaderBrand: adding iconAlt optional attribute

I think this is ok as first pass but probably will add more follow ups for other components in this area.

The main structure of the PR is ok, but I'd recommend to remove all the `<title>` tags from the icons as suggested inline.

2022-10-11 07:04 UTC, dej611 commented on stories/Header/CompleteHeader/basic.tsx
> +  { theme?: 'light' | 'dark' | ''; iconName: string; iconAlt?: string },
Can you pass an alt string also here to use this prop? https://github.com/italia/design-react-kit/pull/864/files#diff-5cd1ad6642e2f768061589327cb5b6e68233f59a39f80814afbc11b816a6c22aL250

2022-10-11 07:13 UTC, dennybiasiolli commented
Thanks for the comments, will work on them 😉

2022-10-11 09:34 UTC, dennybiasiolli commented on src/Icon/assets/ItArrowDown.tsx
> +      <title>Arrow down icon</title>
Ok great, I'm trying to change them in that repo.
In the `1.x` branch there is already a `<title>` element in SVGs, but it's not "ported" to react components with `svgr` command, even if I add `--title-prop` parameter to the command.
Any suggestion here?
I can add `--title-prop` nonetheless, so we will have `title` props in every icon 😉

2022-10-13 07:37 UTC, dej611 commented
Thanks for the updates. I hope to check it tomorrow, and hopefully approve it 👍

2022-10-13 07:39 UTC, dennybiasiolli commented
Thanks! Meanwhile I rebased this PR on top of current `master` branch 😉

2022-10-17 07:02 UTC, dej611 approved these changes
Dived into the SVGR title prop problem and fixed it into another branch.
This PR is approved and will send a follow up with the `title` fix later on. 👍

2022-10-17 07:18 UTC, merged

2022-10-17 07:18 UTC, dej611 commented
Thanks @dennybiasiolli for the PR! 🎉